### ISSUE TITLE
Wrong casing in suggestions at start of sentence

### ISSUE THREAD

**Issue by TanVD** [TanVD/Grazi#17]
In case you have a suggestion at start of sentence (for example, `Proxy is...`) you'll be suggested with `A Proxy`. We need to lowercase next word in that case

**Comment by Fatalll** [comment]
Can not reproduce

**Comment by TanVD** [comment]
Reproducable example:
![Снимок экрана от 2019-07-14 00-19-27](https://user-images.githubusercontent.com/10253437/61176658-1fafbb80-a5cd-11e9-9658-2c30b66331ae.png)
![Снимок экрана от 2019-07-14 00-19-35](https://user-images.githubusercontent.com/10253437/61176659-1fafbb80-a5cd-11e9-8359-5f51bc30ac0a.png)

**Comment by Fatalll** [comment]
Done, if capital letter in the middle of a sentence, then we consider this is a proper name and don't lowecase it.
![image](https://user-images.githubusercontent.com/4066557/61373700-25deba00-a8a3-11e9-92b3-07c1b6f79c6b.png)
