### ISSUE TITLE
Take into account injected languages

### ISSUE THREAD

**Issue by Undin** [TanVD/Grazi#19]
Currently, the inspection doesn't take into account injected language into string literals. That leads to false positive warnings on some syntax constructions.
For example, `..` is the special syntax for ranges in Rust language. And if you inject it into string literal and type `..`, the plugin produces `Punctuation: Use of two consecutive dots or commas` warning although everything is fine
![image](https://user-images.githubusercontent.com/2539310/59159235-40b55600-8acf-11e9-9bfb-a506095170b2.png)

**Comment by TanVD** [comment]
Fixed
