### ISSUE TITLE
edit a 1.43mb file will freeze with high cpu and memory

### ISSUE THREAD

**Issue by bluelovers** [TanVD/Grazi#22]
edit a 1.43mb file will freeze with high cpu 100% and memory

demo file
https://github.com/bluelovers/node-segment-dict/blob/master/dict/segment/dict.txt

**Comment by TanVD** [comment]
Well, for now the solution will be to disable deep grammar check for such a big files that do not have any semantics (in case of markup languages we perform check per language construct and do not have problems with enormously big texts, but the PsiPlainText have no PSI tree basically)

**Comment by TanVD** [comment]
Fixed
