### ISSUE TITLE
Support JavaScript and JSON

### ISSUE THREAD

**Issue by delagen** [TanVD/Grazi#24]
Seems it totally ignored strings in this formats.
But comments are checked well.

**Comment by TanVD** [comment]
Hi, @Delagen. Yep, JS and JSON not supported for now. We will support it in the next updates :)

**Comment by TanVD** [comment]
Support of Json and JavaScript will be in 2019.1-3/2019.2-3.
ETA - before the start of July.

**Comment by TanVD** [comment]
Fixed
