### ISSUE TITLE
Support Latex

### ISSUE THREAD

**Issue by jebacpogotowietylkobukmozemnieleczyc** [TanVD/Grazi#26]
There is a great plugin for latex support in IntelliJ - TeXiFy IDEA.
Would it be hard to implement support for latex in Grazi?
For now, it's only working in comments.

**Comment by TanVD** [comment]
I will take a look at PSI structure of TeXiFy. I hope it шы similar to other already supported plugins. 
In this case it should not be very complex task :)

**Comment by lankabel** [comment]
I just installed Grazi in the hope it can spellcheck LaTex.
I was a bit sad when I noticed that it's not working, but I'm happy that it is a possible/planned upgrade.
Do you have any timeline for it?

**Comment by TanVD** [comment]
I would expect implementation in a few days, definitely before 15 July.

**Comment by TanVD** [comment]
Implemented it in master. 
After tests, it will be released into DEV channel and then to stable.
