### ISSUE TITLE
Move to Kotlin DSL for UI

### ISSUE THREAD

**Issue by TanVD** [TanVD/Grazi#28]
Right now we are using Swing XMLs to describe configuration menu of plugin. This is the only part of Java code in project. 
We need to move to Kotlin DSL from XML.

**Comment by Fatalll** [comment]
Unfortunately Kotlin DSL has no support in 2019.1, so for now only Kotlin

**Comment by TanVD** [comment]
We can say we've moved to DSL, but to our own. Closed for now :)
