### ISSUE TITLE
Autoreload files after configuration changes

### ISSUE THREAD

**Issue by Fatalll** [TanVD/Grazi#38]
Right now users need to reopen files to apply new changes in configuration

**Comment by TanVD** [comment]
As a start we can use for it `DaemonCodeAnalyzer.getInstance(project).restart()`. It should be added to GraziLifecycle

**Comment by TanVD** [comment]
Yep, restart of a daemon approved by IDEA team

**Comment by Fatalll** [comment]
Done, [PR](https://github.com/TanVD/Grazi/pull/39)

**Comment by TanVD** [comment]
Fixed
