### ISSUE TITLE
Support Go

### ISSUE THREAD

**Issue by TanVD** [TanVD/Grazi#51]
Need to introduce support of Go: comments, string literals, GoDoc

**Comment by nikonor** [comment]
It's very important for me!!

**Comment by TanVD** [comment]
Ok, we've got unexpected problems implementing Go. Somehow it affects integration with Kotlin and Python plugin. 
We are investigating it.

**Comment by TanVD** [comment]
You can track progress in PR #60

**Comment by TanVD** [comment]
Fixed and released in 2019.3-5.3.stable
