### ISSUE TITLE
How to compile this project?

### ISSUE THREAD

**Issue by hengzhe-zhang** [TanVD/Grazi#57]
I had submitted a bug and bug had been fixed. But I don't know how to build this project, because I am a Maven user. Is there any build instruction document or ready-made nightly build package?

**Comment by hengzhe-zhang** [comment]
I found an answer by myself. But it's too regret that current master branch is developed on IntelliJIDEA 2019.1.
![image](https://user-images.githubusercontent.com/18747119/61990560-70b3bb00-b075-11e9-8253-a820a5659991.png)

**Comment by TanVD** [comment]
Hi, yep, you should use `buildPlugin`. Master right now is 2019.1, but branch `dev-2019.2` contains code for 2019.2.
Note, that basically you may not compile plugin yourself. We are releasing dev version of plugin each few days.
You just need to set up `https://plugins.jetbrains.com/plugins/dev/list` channel in accordance with manual from here https://www.jetbrains.com/help/idea/managing-plugins.html

**Comment by TanVD** [comment]
Added info on dev versions in README.md
