### ISSUE TITLE
Broken spellcheck for languages except English

### ISSUE THREAD

**Issue by joyful-code** [TanVD/Grazi#67]
After the last update to Version 2019.2-3 Grazi does not recognize German language and marks all correctly written words as wrong. It then suggests English words for correction instead of German. German language is enabled in the settings, tried with both versions (German and Austrian). Also tried on a new Phpstorm installation. OS is Windows 7.

**Comment by TanVD** [comment]
Hi! 
It sounds like a problem with a LangDetector. Workaround is to disable English and remain only German in languages.

We are working on integration of a new, a lot more accurate language detector into Grazi. Unfortunately, it probably will be available only in the release after next.

I can investigate specifically your problem if you would be able to send me exact file that works wrong. 

In the end, update to the latest version. It may solve problem if you are using Markdown (but may not)

**Comment by joyful-code** [comment]
Hello,
I have tried your workaround without luck. Any German text, no matter what text, will not be marked correctly in different file formats. So far I have tried .txt, .md, .html. 
Thank you for your attention.

**Comment by TanVD** [comment]
Ok, we've located the problem. It affects only spellchecking, you can try to disable it in Grazi and in IDEA for now. 
On our side we are working on fixing spellcheck for non-English languages.

**Comment by TanVD** [comment]
Fixed in master

**Comment by TanVD** [comment]
Fix released in a dev version

**Comment by TanVD** [comment]
Fixed and released in 2019.3-5.3.stable
