### ISSUE TITLE
Question: How to switch between languages?

### ISSUE THREAD

**Issue by barseghyanartur** [TanVD/Grazi#78]
How to switch between languages?

My use-case:

- I use PyCharm professional (latest).
- I have enabled two languages: English (GB) and Dutch.
- Doc-strings in Python files are written in English. Some HTML templates are in Dutch. Markdown documentation is written in both. 
- I want to check spelling for my templates (Dutch). I only get English suggestions.

What I expect:

- To be able to define per type of file which languages shall it be checked against.
- To be able to define per file which languages shall it be checked against.

Thanks in advance!

**Comment by barseghyanartur** [comment]
Update: It seems to work (not the switching, but using of more than one language) in latest dev version. 

Please, make a stable release. :)

**Comment by TanVD** [comment]
Great that it works in dev :) We are preparing stable release. Unfortunately this release includes a big load of different improvements and it takes time to verify. On the other hand, new version will, for example, weight around 9mb instead of 160 :)
