### ISSUE TITLE
Feature request: Enable/disable rules for specific file types

### ISSUE THREAD

**Issue by barseghyanartur** [TanVD/Grazi#79]
In Python this is totally valid:

```python
def my_check_func(key, value):
    """Description for my check function.

    Performs the following checks:

    - Describe what the first check is about.
    - Describe what the second check is about. Perhaps some
      more description.
    - And so on.
    """
        # Do something
```

`Grazi` would complain about special characters at the end of paragraph. Although this would
be totally appropriate in `.md` or `.rst` (or any other text file), for code (`.py`) things are slightly different. Agree?

Thus, it would be really great to be able to say "ignore the rule for `.py` files" (or any other file type) option.

**Comment by TanVD** [comment]
Yeah, it is a good idea!
Please, vote for it in an IntelliJ IDEA YouTrack: https://youtrack.jetbrains.com/issue/IDEA-222812

**Comment by barseghyanartur** [comment]
Done.

**Comment by TanVD** [comment]
Fixed during bundling in IntelliJ IDEA
