### ISSUE TITLE
  New repository is https://github.com/JetBrains/intellij-plugins/tree/master/grazie leads to 404

### ISSUE THREAD

**Issue by Gustry** [TanVD/Grazi#81]
In the readme.md:

> New repository is https://github.com/JetBrains/intellij-plugins/tree/master/grazie

Which is a 404

**Comment by Fatalll** [comment]
Sorry, we have migrated again. We are now bundled with IDEA, so the new link is: https://github.com/JetBrains/intellij-community/tree/master/plugins/grazie
