### ISSUE TITLE
In which repository can I find the rules used for French grammar?

### ISSUE THREAD

**Issue by LLyaudet** [TanVD/Grazi#83]
Hello,

Thanks for your hard work :).
Some grammar rules for French language are dumb, curious or strange,
telling that French will disappear...
Examples:
![image](https://github.com/TanVD/Grazi/assets/4527928/65d37fc4-4ada-4ef3-88ea-99aae1f7cb0c)
 
![image](https://github.com/TanVD/Grazi/assets/4527928/b27c2b40-5428-4e42-9438-48c72e995419)

I would like to laugh at the right persons, please ;) XD
Best regards,
    Laurent Lyaudet

**Comment by LLyaudet** [comment]
I have found this repository : https://github.com/languagetool-org/french-pos-dict/tree/master but it is not what I'm looking after :)

**Comment by LLyaudet** [comment]
![image](https://github.com/TanVD/Grazi/assets/4527928/35c163e7-3455-4b16-be67-21371682b782)
 Another example : very nice "Tu sort" ;)

**Comment by LLyaudet** [comment]
Just for the fun and posterity:
![image](https://github.com/TanVD/Grazi/assets/4527928/a22afc74-892b-4b8e-9262-bccc059099eb)
XD

**Comment by LLyaudet** [comment]
![image](https://github.com/TanVD/Grazi/assets/4527928/9675576c-1174-405b-88c8-18123fe52695)
One of the 6 "Correct" sentences is wrong:
"Bob s'est senti honteux de s'être fait moquer devant des filles."
->
"Bob s'est senti honteux d'avoir été moqué devant des filles."
I can help if I know where to push a PR :)

**Comment by Fatalll** [comment]
Hello! Thank you for showing interest in our plugin! Unfortunately, this is an obsolete repository and will be archived soon. The current Grazie plugin is located inside [intellij-community](https://github.com/JetBrains/intellij-community/tree/master/plugins/grazie) sources. Also, we use [LanguageTool](https://languagetool.org/fr) under the hood, and most rules you are seeing come from it. If you are willing to contribute, grammar rules for French can be found [here](https://github.com/languagetool-org/languagetool/blob/master/languagetool-language-modules/fr/src/main/resources/org/languagetool/rules/fr/grammar.xml). There is [some info](https://dev.languagetool.org/development-overview) on how to do that. We will eventually update LanguageTool version inside our IDEs.
